language: python
python:
- 3.6
before_install:
- pip install codecov pytest-cov pyyaml click clockifyclient python-dateutil
install:
- pip install -U tox-travis
script:
- tox
- pytest --cov-report= --cov=.
after_success:
- codecov
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: sjoerdk
  password:
    secure: W7Qd+KVzcb9G8trWazHXt+2yYGwtJxdXjY2Z3WJmqvtZCmJnR3VxbB/AhCP4JYZXJx8Evk9fs9g5so/u3bzws6afYnloVBL/IdeuMTKtyOZqa7yMiBquQ9bb7+sbJLERsFd3Xz+MYuR6I8NvEsWNf/mz1xWalTzHs7G3SeuMg4e9cQGalx7tAwJBdkFnt1gLdRR4MKGXp+r1UCs0gzHkYbyvptlhD6w7Gb0HxFuzQk41NnxT9K+At6gIG8dx5gl4gsaU23nOz7dLk54tcjVjMIuvsC3g7t7SdCchJ8d8BZYUjRVLQ9EyCnEgNSIgcdxk+/Ij47UFPlg24TfLTB2ljjmsC/Ib5zB8kDZ0V5pI8Rrg6TyQjvOZEajp73Q2Ol8lZCZfoxX79vDtysp2nCsqbB4VC476GSh6UpS3cv33n+fB+x2LqNjhCUdI9vAC5Op6ZPUvpqF1yknYmMJafAI+lES+AAb81u+ZTn2DtG/G6YnfQ9Feax1JxndPeE6Js0vZofJ4PTYhnBu+nYueR5ZNPw/u02zeL5lsleQbFCMI/Bs9vldkX2Pnh2qczURQdNz/Cs0RM93wH5ffNgSlnrZCcfa5BAdpocev6+O8VsfsVm6okzZJxN682ynmIwoHJUqkMv302Z0Bxi4mJqox5l1K56o5qOQ0ruyLZ7DriQJ0Pfk=
  on:
    tags: true
    repo: sjoerdk/yeahyeah
    python: 3.6
